// Preview snippet generated by ChatGPT in Rust
fn main() {
    // Lowercase letters
    let lowercase_letters = "abcdefghijklmnopqrstuvwxyz";
    println!("Lowercase Letters: {}", lowercase_letters);

    // Uppercase letters
    let uppercase_letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    println!("Uppercase Letters: {}", uppercase_letters);

    // Numbers
    let numbers = "0123456789";
    println!("Numbers: {}", numbers);

    // Common symbols
    let symbols = "!@#$%^&*()-+=}{[]|\\:;'\"<>,./?`~_";
    println!("Common Symbols: {}", symbols);
}

